J1P5/Meerket_FE

package.json
vite.config.ts
yarn.lock

- #74
```
Internal server error: Failed to resolve import "components/atoms/Icon/BackIcon/BackIcon" from "src/App.tsx". Does the file exist
```
위 오류가 발생하여 vite-tsconfig-paths를 설치 후 적용했습니다.

fix: 파일 경로 가져오기 오류 수정

---

.storybook/main.ts
src/components/atoms/Divider/index.tsx
src/components/atoms/Divider/stories.ts
src/components/atoms/Divider/styled.ts

feat: Divider 컴포넌트 개발

---

src/components/atoms/TabIndicator/index.tsx
src/components/atoms/TabIndicator/stories.ts
src/components/atoms/TabIndicator/styled.ts
src/components/atoms/index.ts

- #7 
Atom의 TabIndicator 컴포넌트 개발
- 생각해보니 props를 type이 아닌 isActive의 boolean 값으로 처리하는 게 더 좋을 것 같아서 임의로 수정해보았습니다..!

feat: TabIndicator 컴포넌트 개발

---

src/types/icon.d.ts

- #8
추가적으로 Icon 타입을 만들었습니다.
- #82

feat: Icon 타입 추가

---

src/components/atoms/Badge/index.tsx
src/components/atoms/Badge/stories.ts
src/components/atoms/Badge/styled.ts

- #11 
- 배지 컴포넌트 개발 완료
- css는 임의로 작성하였습니다.

feat: Badge 컴포넌트 개발 완료

---

src/components/atoms/Label/index.tsx
src/components/atoms/Label/stories.ts
src/components/atoms/Label/styled.ts

- #14
Label 컴포넌트를 개발했습니다.
이후 for(htmlFor)가 필요할 수도 있을 것 같습니다. (input id와 연결!)

feat: Label 컴포넌트 개발 완료

---

src/components/atoms/ImageUpload/index.tsx
src/components/atoms/ImageUpload/stories.ts
src/components/atoms/ImageUpload/styled.ts

- #6 
- ImageUpload 컴포넌트 input 태그로 개발 완료
- onFileChange 부분은 이후에 고도화로 molecule,organism 개발해서 사용하시는 분이 커스텀 부탁드립니다.
- 
선택시

feat: ImageUpload 컴포넌트 개발

---

src/App.tsx

- #87 
queryClient에 타입을 작성했습니다.
Done만 보면 됩니다..! 위에 `WARNING`은 TypeScript 버전때문에 나오는 경고입니다..!

fix: ESLint에 걸리던 App.tsx 수정

---

package.json
src/components/atoms/Toast/ToastItem.tsx
src/components/atoms/Toast/ToastManager.tsx
src/components/atoms/Toast/index.tsx
src/components/atoms/Toast/stories.tsx
src/components/atoms/Toast/styled.ts
src/components/atoms/index.ts
src/hooks/index.ts
src/hooks/useTimeout.ts
src/hooks/useTimeoutFn.ts
yarn.lock

- #13
- Toast 컴포넌트 개발 (Class로 구현)
- 저번에 Chakra UI가 무거워서 직접 구현하자고 얘기가 나왔어서, 일단 라이브러리 사용한 버전은 따로 구현하지 않았습니다.
- 토스트 라이브러리를 쓰지는 않고 **framer-motion과 전역 상태 관리 라이브러리**를 사용하여 직접 구현한 방식을 보았는데, 그것도 좋은 방식인 것 같습니다. 기회가 되면 구현 후 공유하겠습니다.
- 사실 **framer-motion**을 쓰고 싶어서 install 했는데, 결국 아직은 쓰지 않았습니다..! 그치만 나중에 다른 작업하면서 유용하게 쓰일 것 같아 이번 PR을 계기로 추가해 놓겠습니다!
- useTimeout과 useTimeoutFn 훅을 추가했습니다. 나중에 필요하실 때 사용하시면 좋을 것 같습니다!

feat: Toast 컴포넌트 개발

---

src/components/atoms/Button/TextButton/index.tsx
src/components/atoms/Button/TextButton/stories.ts
src/components/atoms/Button/TextButton/styled.ts
src/components/atoms/Button/index.ts
src/components/atoms/TabIndicator/index.tsx
src/components/atoms/Text/index.tsx
src/components/atoms/index.ts

- #12
- TextButton 컴포넌트 개발
- 혹시 몰라서 Text 컴포넌트랑 연결을 하지 않고, font-size는 1rem으로 두었습니다.!

feat: TextButton 컴포넌트 개발

---

src/components/molecules/NavBarItem/index.tsx
src/components/molecules/NavBarItem/stories.ts
src/components/molecules/NavBarItem/styled.ts

- #18 
폴더 이름 잘못입력한거 보고 빠르게 수정해서 올리던 중 merge되어 파일들이 올라가지 않아 다시 올립니다......
- #94

feat: NavBarItem 컴포넌트 개발

---

src/components/atoms/Input/index.tsx
src/components/atoms/Label/index.tsx
src/components/atoms/index.ts
src/components/molecules/LabeledInput/index.tsx
src/components/molecules/LabeledInput/stories.tsx
src/components/molecules/LabeledInput/styled.ts
src/components/molecules/index.ts

- #20
- LabeledInput 컴포넌트 개발
- Label, Input에 htmlFor, id 속성을 추가했습니다. 옵셔널로 주어 스토리북은 따로 수정하지 않았습니다.

feat: LabeledInput 컴포넌트 개발

---

src/components/atoms/Label/index.tsx
src/components/atoms/Select/index.tsx
src/components/molecules/LabeledInput/index.tsx
src/components/molecules/LabeledSelect/index.tsx
src/components/molecules/LabeledSelect/stories.tsx
src/components/molecules/LabeledSelect/styled.ts
src/types/index.ts
src/types/selectOption.d.ts

- #21
- LabeledSelect 컴포넌트 개발
- 사실 한 건 없고...ㅎ 인터페이스의 주석을 조금 수정했습니다.
- 아 ISelectOption을 type으로 옮겼는데, 이름도 iSelectOption.d.ts으로 수정하는 게 나을까요?

feat: LabeledSelect 컴포넌트 개발

---

src/components/atoms/TabIndicator/index.tsx
src/components/molecules/TabItem/index.tsx
src/components/molecules/TabItem/stories.ts
src/components/molecules/TabItem/styled.ts

- #19
TabItem 컴포넌트 개발입니다.
- **NavBarItem에서는 active, default 상태를 type**으로 받았는데 **TabItem에서는 state**로 받았습니다. 같은 역할을 하는 컴포넌트인데 **동일하게 가져가는 것이 좋을지 고민**입니다.

feat: TabItem 컴포넌트 개발

---

src/components/atoms/Image/index.tsx
src/components/atoms/Image/stories.tsx
src/components/atoms/Image/styled.ts
src/components/molecules/RoundImageWithText/index.tsx
src/components/molecules/RoundImageWithText/stories.tsx
src/components/molecules/RoundImageWithText/styled.ts
src/constants/imgPath.ts

- #25
- #9 
RoundImageWithText 컴포넌트 작업했습니다.
- Image 컴포넌트를 수정했습니다. 자세한 내용은 [여기](https://github.com/prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE/issues/9#issuecomment-2497184579)를 참고해주세요.
- 스토리북 max-width는 300px로 설정되어있습니다.

feat: RoundImageWithText 컴포넌트 개발

---

src/components/molecules/IconWithText_Compound/index.tsx
src/components/molecules/IconWithText_Compound/stories.tsx

- #17
- #99
컴파운드 패턴 관련해서 수정했습니다. 
자세한?? 내용은 [여기](https://github.com/prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE/issues/17#issuecomment-2497898158) 참고해주세요.

feat: 컴파운드패턴 스토리북 적용

---

src/components/molecules/TextWithImage/index.tsx
src/components/molecules/TextWithImage/stories.ts
src/components/molecules/TextWithImage/styled.ts
src/components/molecules/index.ts
src/constants/imgPath.ts

- #26
- TextWithImage 컴포넌트 개발
- 말줄임은 2줄까지로 설정했습니다.

feat: TextWithImage 컴포넌트 개발

---

src/components/molecules/InputWithButton/index.tsx
src/components/molecules/InputWithButton/stories.tsx
src/components/molecules/InputWithButton/styled.ts

- #22
InputWithButton 컴포넌트 개발입니다.
- 디자인 나오면 수정 필요합니다.

feat: InputWithButton 컴포넌트 개발

---

src/components/atoms/ImageUpload/index.tsx
src/components/atoms/ImageUpload/stories.ts
src/components/atoms/ImageUpload/styled.ts
src/components/molecules/UploadedImageCounter/index.tsx
src/components/molecules/UploadedImageCounter/stories.tsx
src/components/molecules/UploadedImageCounter/styled.ts

- #30 
- #6
UploadedImageCounter 컴포넌트 개발했습니다.
- [ImageUpload 컴포넌트](https://github.com/orgs/prgrms-web-devcourse-final-project/projects/1/views/6?pane=issue&itemId=87912557&issue=prgrms-web-devcourse-final-project%7CWEB1_1_J1P5_FE%7C6)를 수정했습니다.

feat: UploadedImageCounter 컴포넌트 개발

---

src/components/organisms/AuctionTimer/index.tsx
src/components/organisms/AuctionTimer/stories.ts
src/components/organisms/AuctionTimer/styled.ts
src/utils/dayFormatter.ts

- #34
- #3
- AuctionTimer 컴포넌트 개발
- 00초가 안 나오는 부분과 마감시간 텍스트를 컴포넌트에서 처리하려고 유틸 함수를 살짝 수정했습니다!

feat: AuctionTimer 컴포넌트 개발

---

src/components/atoms/Icon/DownIcon/index.tsx
src/components/atoms/Icon/DownIcon/stories.ts
src/components/atoms/Icon/index.ts
src/components/molecules/IconWithText/index.tsx
src/components/organisms/Header/index.tsx
src/components/organisms/Header/stories.ts
src/components/organisms/Header/styled.ts

- #47
- #8 , #17 
Header 컴포넌트 개발했습니다.
- Icon에 새로운 아이콘인 DownIcon을 추가했습니다.
- 컴파운드 패턴이 적용된 IconWithText에 onClick props를 추가했습니다.
- Header 컴포넌트를 사용하는곳이 공통 레이아웃 컴포넌트일텐데 해당 위치에서 pathname에 따른 type만 변경되는 것을 생각하고 모든 props를 필수로 받도록 만들었습니다. (각각의 onClick 함수들이 페이지 이동 함수라서 그냥 냅둔 느낌입니다!!!)
```tsx
<Header
onLocationClick={handleLocationClick} // 내 동네 선택
onNotificationClick={handleNotificationClick} // "/notification"
onSearchClick={handleSearchClick} // notification
title={title} // "default" 각 페이지 타이틀 | "home" 내 동네
type={pathname === "/" ? "home" : "default"}
/>
```

feat: Header 컴포넌트 개발

---

src/components/organisms/Profile/index.tsx
src/components/organisms/Profile/stories.ts
src/components/organisms/Profile/styled.ts

- #35
- #3 #9 
- Profile 컴포넌트 개발
- 이것도 보니까 molecule로 빼고, 온도가 포함된 전체를 Profile로 정의하는 게 나을 것 같다는 생각이 듭니다..!
- 이미지와 텍스트 조합이 많이 보여서 molecule에서 어떻게 정리할지는 나중에 생각해봐도 좋을 것 같습니다.

feat: Profile 컴포넌트 개발

---

src/components/organisms/SearchHistoryItem/index.tsx
src/components/organisms/SearchHistoryItem/stories.ts
src/components/organisms/SearchHistoryItem/styled.ts
src/components/organisms/index.ts

- #67
- SearchHistoryItem 컴포넌트 개발
- 합치는 거... 재밌네요...

feat: SearchHistoryItem 컴포넌트 개발

---

package.json
src/components/organisms/TopBar/index.tsx
src/components/organisms/TopBar/stories.tsx
src/components/organisms/TopBar/styled.ts
vite.config.ts
yarn.lock

- #50
TopBar 컴포넌트 개발했습니다.
- 컴파운드 패턴으로 만들었습니다. Storybook autodocs가 제대로 되지 않아 직접 작성했습니다...... (테스트는 완전 가능합니다)
```tsx
// Default
<TopBar>
<TopBar.BackIcon onBackIconClick={handleBackIconClick} />
<TopBar.Title title={title} />
{icon && ( // 필요없는곳에서는 안쓰면 됨
<TopBar.Icon icon={icon} onIconClick={handleIconClick} />
)}
</TopBar>
// Search: 검색 아이콘 필수!!
<TopBar>
<TopBar.BackIcon onBackIconClick={handleBackIconClick} />
<TopBar.Input
value={value}
setValue={setValue}
placeholder="검색어를 입력하세요."
/>
<TopBar.Icon icon={SearchIcon} onIconClick={handleIconClick} />
</TopBar>
``` 
- 개발하다가 고민했던부분(컴파운드 쓸지 말지, 배치 고민)이나 힘들었던 부분(Component selector)은 [이슈 댓글](https://github.com/prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE/issues/50#issuecomment-2499736509)로 작성했습니다..!

feat: TopBar 컴포넌트 개발

---

src/components/organisms/BlockedUserItem/index.tsx
src/components/organisms/BlockedUserItem/stories.ts
src/components/organisms/BlockedUserItem/styled.ts

- #51 
- BlockedUserItem 컴포넌트 개발 완료, BlockedUserItem 은 차단 사용자 관리에서 하나의 아이템을 의미합니다.
- space-between으로 지정해뒀습니다!

feat: BlockedUserItem 컴포넌트 개발

---

src/components/organisms/ItemDetails/index.tsx
src/components/organisms/ItemDetails/stories.ts
src/components/organisms/ItemDetails/styled.ts
src/utils/dayFormatter.ts

- #36
ItemDetails 컴포넌트 개발했습니다.
- dayFormatter에 있는 함수들의 파라미터를 `Date` => `Date | string`으로 변경했습니다.

feat: ItemDetails 컴포넌트 개발

---

src/components/molecules/TextWithImage/styled.ts
src/components/organisms/NotificationList/index.tsx
src/components/organisms/NotificationList/stories.tsx
src/components/organisms/NotificationList/styled.ts
src/types/index.ts
src/types/notification.d.ts

- #49 
- #26 
NotificationList 컴포넌트 개발했습니다.
- TextWithImage의 스타일을 살짝 수정했습니다. ([이슈 댓글](https://github.com/prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE/issues/26#issuecomment-2502411183))
- Notification 타입을 만들었습니다.
- TextWithImageProps와 별개로 Notification 타입을 만든 이유는 이후 id라던지 화면 출력과 관련 없는 데이터가 들어올 수 있다고 생각해 분리했습니다.

feat: NotificationList 컴포넌트 개발

---

src/components/organisms/PermissionList/index.tsx
src/components/organisms/PermissionList/stories.ts
src/components/organisms/PermissionList/styled.ts

- #57 
- PermissionList 컴포넌트 개발 완료

feat: PermissionList 컴포넌트 개발

---

src/components/organisms/NeighborhoodSelectionList/index.tsx
src/components/organisms/NeighborhoodSelectionList/stories.ts
src/components/organisms/NeighborhoodSelectionList/styled.ts
src/constants/imgPath.ts

- #60 
- NeighborhoodSelectionList 컴포넌트 개발 완료
- 오전에 storybook 켰을 때 이미지 부분이 깨지는거 같아 해당 경로 다시 수정해뒀습니다.

feat: NeighborhoodSelectionList 컴포넌트 개발

---

.github/workflows/deploy.yml
build.sh

- #102 
- Develop 브런치 Vercel 에 Storybook 연결 작업 (organization 레포와 개인 레포 연결하기 위한 PR)
- build.sh 추가
- 깃허브 워크 플로우 deploy.yaml 추가
- 스토리북 url: [meerket-storybook.vercel.app](meerket-storybook.vercel.app)
- 어쩌다 보니 만들어진 사이트: [meerket.vercel.app](https://meerket.vercel.app/) 
- 배포 중에 app에서 remaingTime 부분에서 unused로 에러가 나서 제 개인 레포는 수정했는데, 여기도 지워야 할 것 같습니다..!
- 이 PR이 머지되면 아마 깃허브 액션이 잘 작동되는지 확인할 수 있을 것 같습니다!

chore: Develop 브런치 Vercel 에 Storybook 연결 작업

---

src/components/organisms/SearchHistory/index.tsx
src/components/organisms/SearchHistory/stories.ts
src/components/organisms/SearchHistory/styled.ts
src/components/organisms/SearchHistoryItem/styled.ts

- #33 
- SearchHistory 컴포넌트 개발
- '전체 삭제' 버튼 누르면 콘솔에 출력 되도록 구현
- X 버튼 누르면 해당 아이템의 idx 콘솔에 출력 되도록 구현
지금 `<SearchHistoryItem>` 관련해서 onHistoryItemClick을 줄 때 space-between으로 되어있어서 가운데 공간이 비어있는 문제가 있는데, IconWithText 내부 css를 flex:1 을 주면 해결은 되지만 이 부분이 영향을 줄 수 있을 것 같아 일단 조치하지 않고 방치해뒀습니다.

feat: SearchHistory 컴포넌트 개발

---

src/components/organisms/BlockedUsersList/index.tsx
src/components/organisms/BlockedUsersList/stories.ts
src/components/organisms/BlockedUsersList/styled.ts

- #52 
- 차단 사용자 리스트 개발
- 차단하기, 차단 해제는 눌러도 콘솔에만 찍히고 상태가 변경되지는 않습니다. 아직 이 단계에서는 props로 받고 있기 때문에
더 윗 단계에서 상태 변경이 일어날 것 같습니다.

feat: BlockedUsersList 컴포넌트 개발

---

src/components/organisms/PostImageItem/index.tsx
src/components/organisms/PostImageItem/stories.ts
src/components/organisms/PostImageItem/styled.ts

- #31 
- x 버튼 눌러서 onClick 이벤트 콘솔에 출력
- isThumbnail 로 대표 사진 구분이 가능하도록 개발
- 기존 이슈에 정리한 내용을 보니 PostImageItem 외에 PostImageList가 필요하겠다는 생각이 듭니다.
- ~~PostImageItem 에 X 버튼을 눌러 이미지를 삭제한다고 표현했는데, 그게 아니라 PostImageList가 존재하고, PostImageList를 사용하는 쪽에서 그 책임을 해야할 것 같습니다. 다만 PostImageList는 디자인 시안 나오고 개발해도 늦지않을 것 같습니다. 형태가 어떻게 될지 잘 모르겠어서..~~
-> PostRegisterForm  을 보니 PostImageList 가 없으면 구현이 안 될 것 같네요. 제가 구현하겠습니다!

feat: PostImageItem 컴포넌트 개발

---

src/components/organisms/LocationMap/index.tsx
src/components/organisms/LocationMap/stories.tsx
src/components/organisms/LocationMap/styled.ts
src/components/organisms/Map/index.tsx
src/types/map.d.ts

- #37
- LocationMap 컴포넌트 개발
- Map의 prop인 `isCenterMarkerExist`를 옵셔널로 주어 false일때는 `<Map coord={coord} />`로만 사용하도록 수 정하였습니다.

feat: LocationMap 컴포넌트 개발

---

src/components/organisms/Modal/index.tsx
src/components/organisms/Modal/stories.tsx
src/components/organisms/Modal/styled.ts

- #54
Modal 컴포넌트 개발했습니다.
개발하면서 고민?? 정리??했던 부분 등은 이슈 댓글에 적었습니다.
사용 시 아래처럼 사용할 수 있습니다.
```tsx
const Example = () => {
const [open, setOpen] = useState(false);
return (
<Modal open={open} onClose={() => setOpen(false)}>
<Modal.Background hasClickEvent={false} />
<Modal.Container>
<Modal.Header title="Modal Title" hasCloseButton={true} />
<Modal.Body>
Modal의 Content!!
</Modal.Body>
<Modal.ButtonContainer direction="horizontal" buttons={[{ title: "확인", onClick: () => console.log("click!") }]} />
</Modal.Container>
</Modal>
);
}
```
- **Modal(Root)**: Modal의 open / close를 관리
- **Modal.Background**: Modal의 배경
- **Modal.Container**: 실제 Modal
- **Modal.Header**: Modal의 Header (CloseButton 포함)
- **Modal.Body**: 실제 Modal의 Content가 되는 영역 (Text, Input 등 아무거나 들어갈 수 있음 `React.ReactNode`)
- …

feat: Modal 컴포넌트 개발

---

src/components/organisms/AuctionTimer/index.tsx
src/components/organisms/PostItem/index.tsx
src/components/organisms/PostItem/stories.tsx
src/components/organisms/PostItem/styled.ts
src/hooks/index.ts
src/hooks/useRemainingTimer.ts

- #64
- #34 (로직 분리)
PostItem 컴포넌트 개발했습니다.
- AuctionTimer에서 사용하는 남은 시간 로직을 hook으로 분리했습니다.
- 전체적인 스타일은 그냥 임의로 만들었습니다.
- 이미지 사이즈는 default: 84px, mini: 60px로 정했습니다.
- 예시 스토리는 그냥 전체 다 사용한 버전, mini버전, post list 버전으로 3개만 작성했습니다.

feat: PostItem 컴포넌트 개발

---

src/components/organisms/ChatMessage/index.tsx
src/components/organisms/ChatMessage/stories.ts
src/components/organisms/ChatMessage/styled.ts
src/utils/dayFormatter.ts

- #61 
ChatMessage 컴포넌트 개발했습니다.
- dayFormatter에 `getTime` 함수를 추가했습니다
- `[오전/오후] 00:00` 형식으로 나오는 함수입니다.
- 해당 함수를 추가하면서 getRelativeTime 함수 설명을 리스트로 보일 수 있게 수정했습니다.
| 변경 전 | 변경 후 |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/9da2c181-45cd-4e5e-bfcc-e166c363d7b1) | ![image](https://github.com/user-attachments/assets/6a60c8ec-a6cc-487c-888f-fe7ca6f94e27) |
- Message의 width는 일단 70%를 차지하도록 만들었습니다. 이후 사이즈 보면서 수정 필요합니다.

feat: ChatMessage 컴포넌트 개발

---

src/components/molecules/KebabMenu/styled.ts
src/components/organisms/CommentItem/index.tsx
src/components/organisms/CommentItem/stories.ts
src/components/organisms/CommentItem/styled.ts
src/hooks/useKebabMenuManager.ts

- #38 
- 상세페이지의 문의사항 섹션에 들어가는 CommentItem입니다. (댓글)
- 케밥 메뉴 매니저를 별도로 구성해서 상황에 따라 맞게 사용할 수 있도록 하였습니다.
- 케밥 메뉴 컴포넌트 쪽에 오타 + 메뉴별 크기가 다르게 나오는 문제를 수정하였습니다.

feat: CommentItem 컴포넌트 개발

---

src/components/atoms/Button/IconButton/styled.ts
src/components/atoms/Button/TextButton/styled.ts
src/components/atoms/Icon/styled.ts
src/components/organisms/ProfileRegistrationForm/index.tsx
src/components/organisms/ProfileRegistrationForm/stories.tsx
src/components/organisms/ProfileRegistrationForm/styled.ts
src/types/index.ts
src/types/user.d.ts

- #59
- #8 #15 #12 
ProfileRegistrationForm 컴포넌트 개발했습니다.
- TextButton / IconButton의 요소를 div에서 button으로 변경했습니다.
- TextButton은 이전과 동일했고, IconButton은 모양이 이상해져 확인해보니 Icon 컴포넌트가 i요소로 아이콘을 감싸고있는 형태인데 i 요소의 line-height가 초기화되지 않아 IconWrapper(i)의 line-height 값을 0으로 설정했습니다.
| 변경 전 | 변경 후 |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/a38ff2a0-4466-4858-962b-7f29c76d086a) | ![Image](https://github.com/user-attachments/assets/d674a2e9-3e9a-4cb3-b212-e61272ee135e) |
- 스타일 확인을 위해 Storybook에서 임의로 width=375px, height=680px로 설정해두었습니다.

feat: ProfileRegistrationForm 컴포넌트 개발

---

src/components/organisms/ChatBubble/index.tsx
src/components/organisms/ChatBubble/stories.ts
src/components/organisms/ChatBubble/styled.ts
src/components/organisms/ChatMessage/index.tsx
src/components/organisms/ChatMessage/stories.ts
src/components/organisms/index.ts
src/types/chat.d.ts
src/types/index.ts

- #62
ChatBubble 컴포넌트 개발했습니다.
- Chat 타입을 별도로 분리했습니다.

feature: ChatBubble 컴포넌트 개발

---

src/components/organisms/Map/index.tsx
src/components/organisms/Map/stories.tsx
src/components/organisms/NeighborhoodAuthForm/index.tsx
src/components/organisms/NeighborhoodAuthForm/stories.tsx
src/components/organisms/NeighborhoodAuthForm/styled.ts
src/hooks/useMap.ts
src/types/map.d.ts

- #48 
-  NeighborhoodAuthForm 컴포넌트 개발
- Map에 setCenterCoord와 SetMyCoord를 설정하는 props를 추가했는데, 타입을 뭐를 넣을지 몰라서 아직 `any` 입니다..! 나중에 수정하겠습니다..ㅠ
- 추후에 위경도 좌표를 주소 string? 혹은 object로 가져오는 유틸 함수를 따로 만들어야 할 것 같습니다. 
- 저는 태화강 주변에 살지는 않는데, 가끔 위치를 좀 딴데로 잡는 것 같습니다..! 노트북이라 그런가요.?

feat: NeighborhoodAuthForm 컴포넌트 개발

---

src/components/organisms/ChatMessages/index.tsx
src/components/organisms/ChatMessages/stories.ts
src/components/organisms/ChatMessages/styled.ts

- #63
ChatMessages 컴포넌트 개발했습니다.

feat: ChatMessages 컴포넌트 개발

---

src/components/molecules/ModalBottomSheet/index.tsx
src/components/molecules/ModalBottomSheet/stories.tsx
src/components/molecules/ModalBottomSheet/styled.ts
src/components/molecules/index.ts

- #69
ModalBottomSheet 컴포넌트 개발했습니다.
- 아래 코드처럼 사용하시면 됩니다.
```tsx
const Component = () => {
const [open, setOpen] = useState(false);
return (
<>
<button onClick={() => setOpen(true)}>Open</button>
<ModalBottomSheet open={open} onClose={() => setOpen(false)}>
<Text
variant="h5"
content="ModalBottonSheet 내부 Content 영역입니다"
/>
<Text content="Modal과 동일하게 open, onClose를 받아 스타일을 설정합니다." />
<Text content="children에는 아무거나 올 수 있습니다. (다양한 컴포넌트들)" />
<Text content="className을 지정해 Body 영역 스타일을 변경할 수 있습니다." />
</ModalBottomSheet>
</>
);
};
```

feat: ModalBottomSheet 컴포넌트 개발

---

src/components/organisms/LocationInputBottomSheet/index.tsx
src/components/organisms/LocationInputBottomSheet/stories.tsx
src/components/organisms/LocationInputBottomSheet/styled.ts

- #44
LocationInputBottomSheet 컴포넌트 개발했습니다.
- ModalBottomSheet의 open과 onClose는 동일하게 가져가야합니다.

feat: LocationInputBottomSheet 컴포넌트 개발

---

src/components/molecules/KebabMenu/index.tsx
src/components/molecules/KebabMenu/stories.ts
src/components/organisms/MenuBottomSheet/index.tsx
src/components/organisms/MenuBottomSheet/stories.tsx
src/components/organisms/MenuBottomSheet/styled.ts
src/hooks/useKebabMenuManager.ts
src/types/index.ts
src/types/menu.d.ts

- #72
- #28 #38 (타입 분리)
MenuBottomSheet 컴포넌트 개발했습니다.
- Menu 타입을 분리했습니다.

feat: MenuBottomSheet 컴포넌트 개발

---

src/components/organisms/LocationPicker/index.tsx
src/components/organisms/LocationPicker/stories.tsx
src/components/organisms/LocationPicker/styled.ts
src/components/organisms/NeighborhoodAuthForm/index.tsx
src/components/organisms/NeighborhoodAuthForm/stories.tsx

- #43
- LocationPicker 컴포넌트 개발
- 미어켓 얼굴은 나의 현재 위치고, 미어켓 몸통은 거래 희망 장소 위치입니다.
- 나의 위치는 태화강이지만, 공원에서 거래를 희망하는 경우

 feat: LocationPicker 컴포넌트 개발

---

src/components/organisms/Comment/index.tsx
src/components/organisms/Comment/stories.ts
src/components/organisms/Comment/styled.ts
src/components/organisms/CommentItem/index.tsx
src/components/organisms/index.ts

- #39 
- #38 
Comment 컴포넌트 개발했습니다.
- CommentItem 컴포넌트의 props를 내보내기했습니다.
- 답글..... 어떻게 작성할지 정해야할듯합니다..........ㅎㅎ....

feat: Comment 컴포넌트 개발

---

src/components/atoms/Button/IconButton/index.tsx
src/components/atoms/Button/IconButton/styled.ts
src/components/organisms/ChatItem/index.tsx
src/components/organisms/ChatOverview/index.tsx
src/components/organisms/NeighborhoodAuthForm/index.tsx
src/components/organisms/PostImageManager/index.tsx
src/components/organisms/PostImageManager/stories.tsx

- #156
`yarn build` 시 발생한 오류를 수정했습니다.

fix: Build 오류 수정

---

src/components/organisms/PostItem/styled.ts
src/components/organisms/PostList/index.tsx
src/components/organisms/PostList/stories.ts
src/components/organisms/PostList/styled.ts

- #65 
- PostList 컴포넌트 개발 완료
- 상태는 피그마를 참고해보니 5개 상태가 있는 것 같아 아래와 같이 추가했습니다.
default : 홈/글 목록
completed : 마이페이지 구매/판매 내역 (거래 완료 상태)
Selling : 마이페이지 판매 내역 (판매 중 상태)
Buying : 마이페이지 구매 내역 (입찰 중 상태)
Chat : 채팅
- 공통 부분을 묶으면 코드가 더 줄어들 것 같지만 지금 저 상태가 전부인지에 대한 부분이 확실하지 않아서 굳이 공통 부분 나누지 않고 작업했습니다.
- Default
- Completed 
- Chat
- Selling
- Buying

 feat: PostList 컴포넌트 개발

---

src/components/atoms/Input/index.tsx
src/components/atoms/Input/styled.ts
src/components/atoms/Textarea/index.tsx
src/components/atoms/Textarea/stories.tsx
src/components/atoms/Textarea/styled.ts
src/components/atoms/index.ts

- #170 
- Textarea 컴포넌트 개발
- 최대 글자수는 500으로 제한하였습니다.
- input에도 간단한 스타일과 focus 기능을 추가해 놓았습니다! (id를 name으로 수정하였습니다.!)
- 팔레트를 atom으로 빼서 쓴다는데, 그건 어려워서 lib로 하면 어떨까? 합니다! 어떨까요? 예전에 예진님이 emotion 공통 스타일로 할 수 있다고 말해주신 것도 무엇인지 궁금하네요.!
- https://github.com/velopert/velog-client/blob/master/src/lib/styles/palette.ts
- https://github.com/velopert/velog-client/blob/master/src/lib/styles/themes.ts
- 사용 예시: https://github.com/velopert/velog-client/blob/master/src/components/common/LabelInput.tsx#L37C4-L41C9

feat: Textarea 컴포넌트 개발

---

src/components/atoms/Input/index.tsx
src/components/atoms/Input/styled.ts
src/components/atoms/Select/index.tsx
src/components/atoms/Select/styled.ts
src/components/atoms/Textarea/index.tsx
src/components/atoms/Textarea/styled.ts
src/components/molecules/LabeledInput/index.tsx
src/components/molecules/LabeledInput/styled.ts
src/components/molecules/LabeledSelect/index.tsx
src/components/molecules/LabeledSelect/styled.ts
src/components/molecules/LabeledTextarea/index.tsx
src/components/molecules/LabeledTextarea/stories.tsx
src/components/molecules/LabeledTextarea/styled.ts
src/components/molecules/index.ts

- #171
- LabeledTextarea 컴포넌트 개발
- Label 관련 컴포넌트에 모두 id, name prop을 주고, style을 조금 변경했습니다.
- 지금 모든 컴포넌트에 width: 100%를 넣고있는데, 원래 이렇게 하는 게 맞는지, 아니면 노가다를 하고 있는 건지 모르겠습니다..!

feat: LabeledTextarea 컴포넌트 개발

---

src/components/organisms/BottomNavBar/styled.ts
src/components/templates/EmptyTemplate/index.tsx
src/components/templates/EmptyTemplate/stories.ts
src/components/templates/EmptyTemplate/styled.ts
src/components/templates/HomeTemplate/index.tsx
src/components/templates/HomeTemplate/stories.ts
src/components/templates/HomeTemplate/styled.ts

- #185 
- BottomNavBar 에 space-between이 적용 안되어있어 적용하였습니다.
- 포스트가 0개인 경우일때 보여주는 화면이 없어 EmptyTemplate 이라고 하는 컴포넌트를 별도로 추가하였습니다.
- 디자인 시안에 따라 Icon 버튼이 아니라 Text 버튼을 사용하였습니다.

feat: HomeTemplate 컴포넌트 개발

---

src/components/organisms/Map/index.tsx
src/components/organisms/Map/stories.tsx
src/components/organisms/Map/styled.ts
src/components/templates/TransactionLocationTemplate/index.tsx
src/components/templates/TransactionLocationTemplate/stories.tsx
src/components/templates/TransactionLocationTemplate/styled.ts
src/components/templates/index.ts
src/hooks/useMap.ts
src/types/map.d.ts

- #178
- TransactionLocationTemplate 컴포넌트 개발
- 마커 툴팁 기능이 없었어서, Map에 추가했습니다.

 feat: TransactionLocationTemplate 컴포넌트 개발

---

src/components/templates/EmptyTemplate/index.tsx
src/components/templates/SearchResultsTemplate/index.tsx
src/components/templates/SearchResultsTemplate/stories.ts
src/components/templates/SearchResultsTemplate/styled.ts

- #188 
- 검색결과 리스트 관련 컴포넌트 개발 완료
- Empy Template State 추가

feat: SearchResultsTemplate 컴포넌트 개발

---

src/components/organisms/SearchHistory/index.tsx
src/components/templates/SearchTemplate/index.tsx
src/components/templates/SearchTemplate/stories.ts
src/components/templates/SearchTemplate/styled.ts

- #186 
- SearchHistory 컴포넌트의 문구 '최근 검색' -> '최근 검색어' 로 문구 수정(디자인 시안 반영)
- 최근 검색어가 아예 없는 경우 SearchHistory  컴포넌트가 아예 출력 안되도록 하였습니다.

feat: SearchTemplate 컴포넌트 개발

---

src/components/templates/CategoryTemplate/index.tsx
src/components/templates/CategoryTemplate/stories.ts
src/components/templates/CategoryTemplate/styled.ts
src/components/templates/HomeTemplate/index.tsx
src/components/templates/HomeTemplate/styled.ts
src/components/templates/MarketPriceTemplate/index.tsx
src/components/templates/MarketPriceTemplate/styled.ts

- #187 
- 카테고리 선택 화면 템플릿 컴포넌트 개발 완료
- 기존 개발했던 아래 2개 컴포넌트 관련하여 BottomNavBar 제거 작업도 같이 진행하였습니다. 
이 부분은 Rootlayour 쪽 개발하는 #159 에서 같이 처리될 예정입니다.
- #192
- #185

feat: CategoryTemplate 컴포넌트 개발

---

package.json
yarn.lock

- #183 
- 아직 백엔드 배포 및 API 문서가 최신화 안되서 Stomp 설치만 진행하였습니다.
- Chat 관련 컴포넌트 전부 작업 후 별도로 이슈 파서 진행하겠습니다.

chore: WebSocket 설정

---

src/components/templates/TransactionBuyTemplate/index.tsx
src/components/templates/TransactionBuyTemplate/stories.ts
src/components/templates/TransactionBuyTemplate/styled.ts
src/components/templates/TransactionSellTemplate/index.tsx
src/components/templates/TransactionSellTemplate/stories.tsx
src/components/templates/TransactionSellTemplate/styled.ts

- #189 
- - TransactionTemplate 컴포넌트를 TransactionSellTemplate 와 TransactionBuyTemplate 로 분리하였습니다.
둘은 동일한 구조를 가지고 있는 템플릿입니다만 세부적인 내용은 조금 다릅니다. 
페이지 단위로 분리하기 위해서 분리 진행하였습니다.

feat: TransactionTemplate 컴포넌트 개발

---

index.html
package.json
public/firebase-messaging-sw.js
src/App.tsx
src/hooks/index.ts
src/hooks/useForegroundNotification.ts
src/hooks/usePermission.ts
src/pages/PermissionRequestPage.tsx
src/services/firebase.ts
yarn.lock

- #162
FCM 연동했습니다.
- service worker에서 api key 노출이 있어 걱정되어 검색해보니 [서비스용 API Key라서 크게 문제될 부분은 없을 것 같습니다](https://firebase.google.com/docs/projects/api-keys?hl=ko). 해당 부분은 이후 실제 사용할 firebase application으로 수정 필요합니다.
- 권한 요청을 거부하면 이후 사용자가 **직접** 권한을 승인해야합니다. 웹 브라우저의 경우는 간단하지만 모바일에서는 어떻게될지 한번 확인해봐야할 것 같습니다..ㅠ
- 권한 요청은 permission-request 페이지에서 할 수 있습니다.......!
- 추가적으로 알림 클릭 시 이벤트를 테스트하고있었는데 새창으로는 잘 열리는데 이미 열린 페이지에서 url만 변경하려고 했을 때에는 잘 안됐습니다. 이 부분은 이후 잘 동작하는지 확인이 필요할 것 같습니다.

feat: FCM 연동

---

src/components/molecules/TabMenu/styled.ts
src/components/organisms/ChatItem/styled.ts
src/components/templates/ChatListTemplate/index.tsx
src/components/templates/ChatListTemplate/stories.ts
src/components/templates/ChatListTemplate/styled.ts
src/components/templates/EmptyTemplate/index.tsx
src/components/templates/EmptyTemplate/stories.ts
src/components/templates/HomeTemplate/styled.ts
src/components/templates/MarketPriceTemplate/styled.ts
src/components/templates/SearchResultsTemplate/styled.ts
src/components/templates/TransactionBuyTemplate/stories.ts
src/components/templates/TransactionSellTemplate/stories.tsx

- #190 
- ChatListTemplate 컴포넌트 개발완료
- TabMenu 쪽에 flex-end 가 설정이 안되서 '안 읽은 채팅방' 의 경우 아래 Tab indicator가 어긋나 보이던 현상 해결했습니다. 
- ChatItem 스타일에 min-width가 적용되어 있어 제대로 나오지 않아 제거하였습니다.
- 시세조회, 검색결과, 홈(글 목록) 템플릿에 padding값으로 인해 높이 100vh로 주면 스크롤 생기는 현상 css 조정하였습니다.
- Empty Template 관련하여 타입을 더 추가하였습니다.

feat: ChatListTemplate 컴포넌트 개발

---

src/components/templates/MyPageTemplate/index.tsx
src/components/templates/MyPageTemplate/stories.tsx
src/components/templates/MyPageTemplate/styled.ts

- #179 
- MyPageTemplate 컴포넌트 개발
- 지금 메뉴의 텍스트가 드래그가 되어서 추후에 수정이 필요합니다.

feat: MyPageTemplate 컴포넌트 개발

---

src/components/organisms/ChatOverview/styled.ts
src/components/templates/ChatListTemplate/index.tsx
src/components/templates/ChatListTemplate/stories.ts

- #190 
- 기존 ChatOverview를 하나도 사용하고 있지 않아서 사용하는 형태로 변경하였습니다.

feat: ChatListTemplate 컴포넌트 변경

---

src/components/atoms/Button/LoginButton/styled.ts
src/components/templates/LoginTemplate/index.tsx
src/components/templates/LoginTemplate/stories.tsx
src/components/templates/LoginTemplate/styled.ts

- #164
LoginTemplate 컴포넌트 개발했습니다.
- LoginButton 컴포넌트 max-width 제거했습니다

feat: LoginTemplate 컴포넌트 개발

---

src/components/templates/RootLayout/index.tsx

- #210
TopBar 표시되는 페이지 수정했습니다.
- LoginPage와 PermissionRequestPage에서 TopBar가 보이지 않도록 수정했습니다.

fix: TopBar 표시되는 페이지 수정

---

src/components/organisms/ChatMessages/styled.ts
src/components/organisms/PostList/index.tsx
src/components/templates/ChatRoomTemplate/index.tsx
src/components/templates/ChatRoomTemplate/stories.ts
src/components/templates/ChatRoomTemplate/styled.ts

- #191 
-  ChatRoomTemplate 컴포넌트 개발
- 추구 WebSocket 연결하면서 디자인 수정 예정입니다.

feat: ChatRoomTemplate 컴포넌트 개발

---

src/components/templates/ProfileRegistrationTemplate/index.tsx

실수로 page를 올려서 template을 올립니다......

feat: ProfileRegistrationTemplate 컴포넌트 개발

---

src/services/api.ts
src/services/apis/example.ts
src/types/response/example.d.ts
src/types/response/index.ts

- #217
1. onResponse에서 **isSuccess가 true인 경우에 리턴하는 값을 res.data에서 res로 변경**했습니다.
2. **각 http method에서 res.data를 리턴**하도록 변경했습니다.
- 간단하게 사용 예시 파일을 만들어두었습니다. ( `services/apis/example.ts`, `types/response/example.d.ts` )
빨간줄이 생기는 코드
빨간 줄 없이 깔끔한 코드.....!

fix: Axios Instance 수정

---

src/components/organisms/AuctionControlBar/styled.ts
src/components/templates/DetailTemplate/index.tsx
src/components/templates/DetailTemplate/stories.tsx
src/components/templates/DetailTemplate/styled.ts

- #167 
DetailTemplate 컴포넌트 개발했습니다.
- AuctionControlBar 스타일을 피그마 시안과 최대한 유사하게 만들었습니다. (구조 / 배경 등등.....)
-  판매자 / 구매자로 나누어지는 부분이 AuctionControlBar / TopBar에서 케밥 클릭뿐이라 그냥 구분하지 않았습니다.
- AuctionControlBar의 경우 페이지에서 넘기는 데이터(bids, buttons)에서 처리됩니다....!

feat: DetailTemplate 컴포넌트 개발

---

src/components/organisms/BlockedUserItem/stories.ts
src/components/organisms/LocationPicker/index.tsx
src/components/organisms/LocationPicker/stories.tsx
src/components/organisms/LocationPicker/styled.ts
src/components/organisms/NeighborhoodAuthForm/index.tsx
src/components/templates/MyPageTemplate/stories.tsx
src/components/templates/NeighborhoodAuthTemplate/index.tsx
src/components/templates/SelectLocationTemplate/index.tsx
src/components/templates/SelectLocationTemplate/stories.tsx
src/components/templates/SelectLocationTemplate/styled.ts

- #177
- SelectLocationTemplate 컴포넌트 개발
- 하는 김에 빌드 에러 수정도 여기서 같이 작업했습니다.
- 페이지 연결 후에 레이아웃 수정이 필요합니다.

feat: SelectLocationTemplate 컴포넌트 개발

---

src/components/atoms/Input/index.tsx
src/components/organisms/PostRegisterForm/index.tsx
src/components/organisms/PostRegisterForm/styled.ts
src/components/templates/PostRegisterTemplate/index.tsx
src/components/templates/PostRegisterTemplate/stories.tsx
src/components/templates/PostRegisterTemplate/styled.ts
src/constants/categories.ts
src/constants/options.ts
src/types/category.d.ts
src/types/index.ts

- #176 
- PostRegisterTemplate 컴포넌트 개발
- 페이지 만들 때, 3일 후, 2일 후 등 Select를 선택했을 때의 실제 시간으로 변환하는 유틸 함수가 따로 필요합니다.
- 임의로 카테고리를 상수로 만들어 놓았습니다. 나중에 백엔드 데이터로 수정이 필요합니다.
- constans도 배럴 패턴을 적용하려 했는데, 왠지 모르겠지만 안되어 나중에 한 번 살펴볼 계획입니다.

 feat: PostRegisterTemplate 컴포넌트 개발

---

src/components/templates/NeighborhoodSelectionTemplate/index.tsx
src/components/templates/NeighborhoodSelectionTemplate/stories.tsx
src/components/templates/NeighborhoodSelectionTemplate/styled.ts
src/components/templates/RootLayout/index.tsx
src/hooks/index.ts
src/hooks/useNeighborhoodSelection.ts

- #166
NeighborhoodSelectionTemplate 컴포넌트 개발했습니다.
- geolocation 처리하는 함수 / 위치 권한 요청 함수를 분리하는게 좋을 것 같습니다..! (일단 이대로 두고 이후 수정!)
- 위치 권한 요청 함수는 제가 갑자기 권한 페이지 하다가 가져갈수도 있습니다........!
- 동네 목록을 받아오는 API를 찾지 못해 목록으로 불러오지 못했습니다. 
- 우선은 하나만 가져와서 **최초 => 내 위치 기반 동네**, **이후 => 현재 위치 또는 검색(페이지)으로 동네 선택** 으로 구현할 예정입니다.

feat: NeighborhoodSelectionTemplate 컴포넌트 개발

---

src/App.tsx
src/stores/useModalStore.ts

- #248 
- Modal 전역 상태 관리 추가
- App이 지저분해져서 고도화가 필요합니다.!

feat: Modal 전역 상태 관리 추가

---

src/App.tsx
src/components/molecules/ModalBottomSheet/styled.ts
src/components/organisms/LocationPicker/index.tsx
src/components/organisms/Map/styled.ts
src/components/templates/SelectLocationTemplate/index.tsx
src/components/templates/SelectLocationTemplate/stories.tsx
src/components/templates/SelectLocationTemplate/styled.ts
src/hooks/useMap.ts
src/main.tsx
src/pages/SelectLocationPage.tsx
src/router.tsx
src/stores/index.ts
src/stores/selectedLocationStore.ts

- #236
- SelectLocationPage 컴포넌트 개발
- 모달 관련 무한 루프 에러는 해당 브랜치에서 고쳤습니다!
- 바텀 시트 스타일도 여기서 수정하였습니다. (생각해보니 모달 디자인도 수정이 필요합니다..!)
- 재렌더링 버그는 이슈에 정리해 놓겠습니다.!
- 수정 테스트는 post 등록 페이지가 완성되면 한 번 더 검토하겠습니다.
- 위치 권한 있을 때 
- 위치 권한 없을 때

feat: SelectLocationPage 컴포넌트 개발

---

src/components/organisms/ProfileRegistrationForm/index.tsx
src/components/organisms/ProfileRegistrationForm/stories.tsx
src/components/templates/ProfileRegistrationTemplate/stories.tsx
src/pages/LoginPage.tsx
src/pages/OAuthCallbackPage.tsx
src/pages/index.ts
src/router.tsx
src/services/api.ts
src/services/apis/auth.ts
src/services/apis/index.ts
src/stores/index.ts
src/stores/userStore.ts
src/types/response/auth.d.ts
src/types/response/index.ts
src/types/user.d.ts

- #244
로그인 페이지를 개발했습니다.
- 백엔드 API를 붙이긴 했지만, 현재 result 값이 정해지지 않아 해당 부분은 이후 수정이 필요합니다.

feat: 로그인 페이지 개발

---

src/components/organisms/ChatBubble/styled.ts
src/components/templates/HomeTemplate/styled.ts
src/main.tsx
src/pages/ChatListPage.tsx
src/pages/ChatRoomPage.tsx
src/pages/HomePage.tsx

- #228 
- 이미지 깨지는 부분은 API에 문제가 있어서 그렇습니다.

feat: HomePage 컴포넌트 개발

---

src/components/atoms/Input/index.tsx
src/hooks/useSearchTopBar.ts
src/pages/SearchPage.tsx
src/router.tsx

feat: SearchPage 컴포넌트 개발

---

src/components/organisms/CategoryGrid/index.tsx
src/components/organisms/CategoryGrid/styled.ts
src/components/templates/CategoryTemplate/index.tsx
src/components/templates/CategoryTemplate/styled.ts
src/pages/CategoryPage.tsx
src/pages/SearchResultPage.tsx
src/router.tsx

- #226 
- 정확한 카테고리 내용은 안정해서 임의로 구성하였습니다.
- 카테고리 클릭시 'search/category/:category' 로 이동하도록 변경하였습니다.
- 동일하게 검색어 검색시 'search/keyword/:keyword' 로 이동하도록 변경하였습니다.
- SearchResultPage 도 함께 작업하였습니다.
- #225 도 함께 작업 진행하였습니다.
다만 API가 완전하지 않아서 제대로 된 테스트는 진행하지 못하였습니다.

 feat: CategoryPage 컴포넌트 개발

---

src/components/templates/TransactionBuyTemplate/index.tsx
src/components/templates/TransactionBuyTemplate/styled.ts
src/components/templates/TransactionSellTemplate/index.tsx
src/components/templates/TransactionSellTemplate/styled.ts
src/constants/transaction.ts
src/hooks/useWebSocket.ts
src/pages/TransactionPage.tsx
src/router.tsx

- #224 
- 판매 내역, 구매 내역 API가 개발 완료가 안 되서 가데이터 임시로 넣어놨습니다.
- API 완료 되고 나서 수정이 필요합니다.

feat: TransactionPage 컴포넌트 개발

---

src/components/atoms/Button/TextButton/styled.ts
src/components/atoms/Text/index.tsx
src/components/molecules/IconWithText/index.tsx
src/components/organisms/Header/index.tsx
src/components/organisms/Header/styled.ts
src/components/organisms/PostItem/index.tsx
src/components/organisms/PostItem/styled.ts
src/components/organisms/PostList/index.tsx
src/components/organisms/PostList/styled.ts
src/components/organisms/TopBar/styled.ts

- #260 
- IconWithText  에 Text쪽에 variant 을 파라미터로 받아서 해당 폰트 타입 지정할 수 있도록 변경하였습니다.
1. Home 목록에 expiredTime (마감시간 현재 없음)
2. Home 헤더에 '둘러보기' 없음 
3. 바텀 NavBar 아이콘 작업 필요

chore: HomePage 컴포넌트 디자인 적용

---

src/components/organisms/TopBar/styled.ts
src/components/templates/NeighborhoodSelectionTemplate/index.tsx
src/components/templates/NeighborhoodSelectionTemplate/stories.tsx
src/hooks/useNeighborhoodSelection.ts
src/pages/NeighborhoodSelectionPage.tsx
src/services/apis/activityAreas.ts
src/services/apis/index.ts
src/types/response/activityAreas.d.ts
src/types/response/index.ts

- #246 
동네 선택 페이지 개발했습니다. 
- GET쪽 API 연동도 완료입니다. 현재 POST에서 500에러가 발생하지만 해당 부분은 프로필 등록 이후 확인할 예정입니다.

feat: 동네 선택 페이지 개발

---

src/components/organisms/BlockedUserItem/index.tsx
src/components/organisms/BlockedUserItem/stories.ts
src/components/organisms/BlockedUsersList/index.tsx
src/components/organisms/BlockedUsersList/stories.ts
src/components/templates/BlockedUsersTemplate/index.tsx
src/components/templates/BlockedUsersTemplate/stories.tsx
src/components/templates/EmptyTemplate/index.tsx
src/pages/BlockedUsersPage.tsx
src/types/profile.d.ts

- #241
- BlockedUsersPage 컴포넌트 개발
- onClick을 IBlockedUserItem에서 분리하였습니다.
- api가 개발되면 작업을 재개할 것 같습니다.

feat: BlockedUsersPage 컴포넌트 개발

---

src/components/organisms/PostRegisterForm/index.tsx
src/components/organisms/PostRegisterForm/stories.tsx
src/components/templates/BlockedUsersTemplate/stories.tsx
src/components/templates/MyPageTemplate/stories.tsx
src/components/templates/PostRegisterTemplate/index.tsx
src/components/templates/PostRegisterTemplate/stories.tsx
src/pages/BlockedUsersPage.tsx
src/pages/PostRegisterPage.tsx
src/types/post.d.ts

fix: 빌드 에러 수정

---

src/components/organisms/CommentItem/index.tsx
src/components/templates/DetailTemplate/index.tsx
src/components/templates/DetailTemplate/stories.tsx
src/hooks/index.ts
src/hooks/useCommentWriter.ts
src/hooks/useFetchComment.ts
src/hooks/useFetchProduct.ts
src/pages/DetailPage.tsx
src/pages/DetailPage/index.tsx
src/pages/DetailPage/styled.ts
src/services/apis/comment.ts
src/services/apis/product.ts
src/types/response/product.d.ts

- #247
상세페이지 작업했습니다.
- 상세 페이지 불러오는 API 붙였고, 댓글 조회, 작성, 수정 붙어있습니다. (삭제는 붙여놓긴했는데 일단 닉네임 이후 확인 필요합니다)
- 입찰쪽 기능 아직 못했습니다.
- 모달 못했습니다.
- 일단 디자인 없이 작업중입니다.

feat: 상세페이지 개발 (2차)

---

src/components/atoms/Button/LoginButton/styled.ts
src/components/atoms/Icon/LocationIcon/index.tsx
src/components/organisms/NeighborhoodSelectionList/index.tsx
src/components/organisms/NeighborhoodSelectionList/styled.ts
src/components/organisms/ProfileRegistrationForm/styled.ts
src/components/organisms/TransactionOverview/styled.ts
src/components/templates/EmptyTemplate/index.tsx
src/components/templates/NeighborhoodSelectionTemplate/index.tsx
src/components/templates/NeighborhoodSelectionTemplate/styled.ts
src/pages/ChatRoomPage.tsx

- #283 
- 동네 설정 디자인 반영도 추가로 진행하였습니다.
- 로그인 쪽 버튼 높이 디자인 시안과 일치 시켰습니다.
- 프로필 등록 쪽 버튼 높이 디자인 시안과 일치 시켰습니다.

chore: 버튼 사이즈 통일 디자인 작업

---

src/components/atoms/Icon/ReplyIcon/index.tsx
src/components/atoms/Icon/ReplyIcon/stories.ts
src/components/atoms/Icon/index.ts
src/components/molecules/InputWithButton/index.tsx
src/components/molecules/KebabMenu/index.tsx
src/components/molecules/KebabMenu/styled.ts
src/components/organisms/Comment/index.tsx
src/components/organisms/Comment/stories.tsx
src/components/organisms/Comment/styled.ts
src/components/organisms/CommentItem/index.tsx
src/components/organisms/CommentItem/stories.tsx
src/components/organisms/CommentItem/styled.ts
src/components/templates/DetailTemplate/styled.ts

feat: 댓글 디자인 적용

---

src/components/atoms/Input/index.tsx
src/components/organisms/PostRegisterForm/index.tsx
src/components/organisms/PostRegisterForm/stories.tsx
src/components/templates/PostRegisterTemplate/stories.tsx
src/pages/PostRegisterPage.tsx
src/types/post.d.ts

- #235
- 몇몇 부분을 수정했는데, 나중에 구체적으로 작성하겠습니다!
- input 숫자 3자리 , 로 수정
- 조금 수정해서

 feat: PostRegisterPage 컴포넌트 개발 (2차)

---

src/components/atoms/Button/TextButton/index.tsx
src/components/atoms/Button/TextButton/styled.ts
src/components/atoms/Icon/ReplyIcon/index.tsx
src/components/organisms/AuctionBidBottomSheet/index.tsx
src/components/organisms/AuctionBidBottomSheet/styled.ts
src/components/organisms/AuctionControlBar/index.tsx
src/components/organisms/AuctionControlBar/styled.ts
src/components/organisms/AuctionTimer/index.tsx
src/components/organisms/AuctionTimer/styled.ts
src/components/organisms/ItemDetails/index.tsx
src/components/organisms/ItemDetails/styled.ts
src/components/organisms/LocationMap/index.tsx
src/components/organisms/LocationMap/styled.ts
src/components/templates/DetailTemplate/index.tsx
src/constants/queryKeys.ts
src/hooks/index.ts
src/hooks/useBid.tsx
src/hooks/useFetchBidding.ts
src/pages/DetailPage/index.tsx
src/services/apis/auction.ts
src/services/apis/index.ts
src/services/apis/product.ts
src/types/response/auction.d.ts
src/types/response/index.ts
src/types/response/product.d.ts

- #247
판매자 프로필을 제외한 디자인은 완료했습니다.
백엔드 API 연동은 입찰쪽 제외 거의 완료했습니다.
- 임사로 입찰내역을 긁어와서 처리했습니다.
- 이후 추가적으로 개발이 필요합니다.

feat: 상세 페이지 작업 (3차)

---

src/pages/guards/AuthGuard.tsx
src/pages/guards/LoginGuard.tsx

fix: RouterGuard 제거

---

src/hooks/useNeighborhoodSelection.ts

fix: 활동 동네 설정 수정

---

src/hooks/useNeighborhoodSelection.ts
src/pages/ProfileRegistrationPage.tsx

- #296
로그인 이후 흐름에 맞게 작동하도록 수정했습니다.
- 프로필 url은 적용하지 못했습니다. 이후 지금 상태로 된다면 profile 화면에서 적용해야할듯합니다....

fix: 흐름에 맞게 수정

---

src/pages/MyPage.tsx
src/pages/OAuthCallbackPage.tsx
src/stores/userStore.ts
src/types/response/user.d.ts
src/types/user.d.ts

- #238
- api 코드를 추가하고, 리팩터링하였습니다.
- 예진님 api 코드로 수정하였습니다.
- emdId를 추가하였습니다.
- setUser에서 프로필 사진이 없으면 로고를 띄우도록 useUserStore를 소폭 수정하였습니다.

 feat: MyPage 컴포넌트 개발

---

src/components/organisms/PostRegisterForm/index.tsx
src/components/templates/PostRegisterTemplate/index.tsx
src/pages/PostRegisterPage.tsx
src/services/apis/product.ts
src/stores/formDataStore.ts
src/types/post.d.ts
src/types/response/product.d.ts

- #235
- api, type으로 리팩터링 했습니다.
- api 부분은 백엔드에서 webp 확장자를 지원하지 않아서, 연동 테스트를 한 번 더 진행해 볼 생각입니다.
- 예전보다는 나아졌지만, 코드가 아직도 많이 지저분합니다...
- `minimumPrice`를 ,가 있는 상태로, Number()를 하면 NaN이 되기 때문에 replace 작업이 필요했습니다.

 feat: PostRegisterPage 컴포넌트 개발 (3차)

---

src/components/atoms/Text/index.tsx
src/components/atoms/Text/styled.ts
src/components/organisms/PostItem/index.tsx
src/components/organisms/PostItem/styled.ts
src/components/organisms/PostList/index.tsx
src/components/organisms/PostList/styled.ts
src/components/organisms/PostRegisterForm/index.tsx
src/components/templates/TransactionSellTemplate/index.tsx
src/pages/TransactionPage.tsx
src/styles/theme.ts

chore: 판매 내역 디자인 적용

---

src/hooks/useBid.ts
src/pages/DetailPage/index.tsx
src/pages/DetailPage/styled.ts

- #247
자잘한 오류들 수정했습니다.
- 거래 희망 장소 페이지로 이동하기 전에 location과 coord를 넣어서 보내도록 수정했습니다.

feat: 상세페이지 작업 (5차)

---

src/components/atoms/Toast/styled.ts
src/components/organisms/ProfileRegistrationForm/index.tsx
src/pages/ProfileRegistrationPage.tsx

- #307
- 닉네임 중복확인 처리
- 닉네임 15자 이상 시 경고 메시지 추가
- 디자인적으로 토스트가 어느 위치에서 어떻게 튀어나오는게 좋을지 자문이 필요합니다.

fix: 닉네임 중복확인 처리

---

src/components/atoms/Input/styled.ts
src/components/molecules/LabeledInput/styled.ts
src/components/organisms/ChatMessages/styled.ts
src/components/organisms/PostItem/index.tsx
src/components/organisms/PostList/index.tsx
src/components/organisms/TopBar/styled.ts
src/pages/ChatRoomPage.tsx
src/pages/NeighborhoodAuthPage.tsx
src/utils/dayFormatter.ts

- #304
- 동네인증 쪽 검색 바 지워야함
- 채팅 쪽 채팅 바 fixed로 변경
- 헤더 - input 창 크기 고정(변경)
- 채팅 방 물품 정보 데이터 추가 후 API 연동

chore: 판매 내역 및 기타 디자인 적용

---

src/components/organisms/PostImageManager/index.tsx
src/components/organisms/PostRegisterForm/index.tsx
src/components/templates/SelectLocationTemplate/index.tsx
src/pages/DetailPage/index.tsx
src/pages/PostRegisterPage.tsx
src/pages/SelectLocationPage.tsx
src/stores/formDataStore.ts
src/types/response/product.d.ts
src/utils/dayFormatter.ts

- #235
- 한 컴포넌트 내에서 주스탄드로 set하고 변경된 값을 바로 템플릿에 prop로 반영하고 싶었는데, 그렇게 하는 게 안되는지 해결할 수 없었습니다. 
- 그래서 현재는 상세페이지에서 주스탄드로 값을 넣어주고, 그걸 빼오는 식으로 구현하였습니다... 문제가 많습니다...
- 불러오는 시간이 Select에 제대로 반영이 안된 부분은 수정 완료하였습니다.!

 feat: PostRegisterPage 컴포넌트 개발 (4차)

---

src/components/organisms/NeighborhoodAuthForm/index.tsx
src/components/organisms/UserLocationBottomSheet/index.tsx
src/hooks/useLocationErrorEvent.tsx

- #315
- 추후에 구체적으로 작성하겠습니다.
- 동네인증 위치권한X인 경우 버튼있어서 바깥으로 내보내야 됨
- 동네인증 '그래도 여기로 인증할래요' 문구 조사 필요

fix: 회의 피드백 반영

---

src/components/atoms/Button/TextButton/index.tsx
src/components/organisms/AuctionControlBar/styled.ts
src/components/organisms/Comment/index.tsx
src/components/organisms/Comment/stories.tsx
src/components/organisms/Comment/styled.ts
src/components/organisms/CommentItem/deleted.tsx
src/components/organisms/CommentItem/index.tsx
src/components/organisms/CommentItem/styled.ts
src/components/templates/DetailTemplate/index.tsx
src/hooks/useBid.ts
src/hooks/useCommentWriter.ts
src/pages/DetailPage/index.tsx
src/services/apis/product.ts
src/types/response/comment.d.ts

- #247
상세페이지 작업입니다..!
- 삭제된 댓글 처리 및 댓글쪽 자잘하게 수정했습니다.
- 구매자 있는 경우 예외처리 추가했습니다. (댓글, 게시글)
- 삭제 로직 추가했습니다. (테스트 못했습니다... ㅠㅠ..)
- 조기종료 클릭 후 응답완료 시 토스트 추가했습니다. 그리고 진행중이라는 디자인 추가했습니다. (임의로)

feat: 상세페이지 작업 (7차)

---

src/components/organisms/ProfileRegistrationForm/index.tsx
src/pages/guards/AuthGuard.tsx

- #318
RouterGuard 수정되었습니다.
- 기존 session데이터만 확인하던 부분을 user 데이터도 같이 확인하도록 수정했습니다.
- session 데이터 가져오면서 오류가 발생하면 user 데이터를 null로 설정하도록 수정했습니다.

fix: RouterGuard 수정

---

src/hooks/useFetchSession.ts
src/pages/guards/AuthGuard.tsx

- #318
push 안하고 merge해버려서 다시 올립니다..!

fix: session 가져올 때 에러나면 user 데이터 null

---

src/components/templates/MyPageTemplate/index.tsx
src/components/templates/MyPageTemplate/styled.ts
src/pages/MyPage.tsx

- #323
- 로그아웃 버튼 추가
- 현재는 그냥 클릭하면 바로 로그아웃이 되어 너무 쉽게 보내주는 것 같아서, 진짜 로그아웃할건지 모달을 하나 더 만들 생각입니다.

feat: 로그아웃 버튼 추가

---

src/components/organisms/PostRegisterForm/index.tsx
src/components/templates/RootLayout/index.tsx
src/hooks/useLocationErrorEvent.tsx
src/pages/DetailPage/index.tsx
src/pages/PostRegisterPage.tsx
src/pages/SelectLocationPage.tsx
src/services/apis/product.ts
src/stores/formDataStore.ts
src/utils/dayFormatter.ts

- #235
- persist 추가
- 자세한 건 나중에 정리하겠습니다.
- startsWith 에러 수정

feat: PostRegisterPage 컴포넌트 개발

---

src/components/templates/RootLayout/index.tsx
src/pages/HomePage.tsx
src/services/apis/product.ts

- #326
- 생각해보니 그냥 홈 페이지의 추가하기 버튼에서 초기화를 하면 되는 거라서 뒤로 가기 버튼은 기존 걸로 바꿨습니다!
- 되게 쉽게 해결할 수 있는 부분을 빙 둘러갔네요..ㅎ

fix: 뒤로 가기 기능 버그 수정

---

src/components/organisms/PostRegisterForm/index.tsx

- #329 
- 최종 입찰가를 최저 입찰가로 수정했습니다.

chore: 최저 입찰가로 수정

---

src/pages/HomePage.tsx

chore: 임시 머지 (에러 미수정)

---

src/components/templates/DetailTemplate/index.tsx

- #247
임의로 만들었던 조기마감에서 최소 입찰가격 부분을 수정했습니다. (조기마감 진행중에는 최소 입찰 가격을 내 입찰 가격으로)

feat: 상세페이지 작업 (9차 - 조기마감)

---

src/utils/dayFormatter.ts

- #327
- dayFormmatter 시간 동기화 미반영 에러 수정
- ISOString() 제거

fix: 시간 오류 수정

---

src/components/organisms/PostRegisterForm/index.tsx
src/pages/HomePage.tsx
src/pages/PostRegisterPage.tsx
src/stores/formDataStore.ts

fix: PostRegisterPage 거래희망장소 선택 시 클리어 버그 수정

---

src/components/organisms/TopBar/index.tsx
src/components/templates/RootLayout/index.tsx
src/hooks/useNeighborhoodSelection.ts
src/hooks/useSearchTopBar.ts
src/pages/NeighborhoodSelectionPage.tsx
src/stores/topbarStore.ts

- #338
검색쪽(useSearchTopBar), 동네검색 페이지
- 엔터 누를 때 onSearch(onEnter,onKeyDown)실행되도록 수정
- 검색어 입력 없이 검색 시 토스트 ("검색어를 입력해주세요.")
- `키워드 검색` 검색어에 특수문자 들어가면 encodeURI 처리

fix: TopBar Input쪽 수정

---

src/components/templates/MyPageTemplate/styled.ts

- #343
- 모바일 환경에서 문제가 생겨서 Style을 수정했습니다.

chore: 프로필 Style 이슈 수정

---

src/components/organisms/AuctionTimer/index.tsx
src/components/templates/DetailTemplate/index.tsx
src/hooks/useFetchProduct.ts
src/hooks/useRemainingTimer.ts
src/pages/DetailPage/index.tsx
src/utils/dayFormatter.ts

- #247
상세페이지 작업입니다.
- 마감 시 AuctionControlBar 숨김처리
- 마감 시 케밥메뉴 클릭하면 "마감된 상품입니다" 토스트

feat: 상세페이지 작업 (10차)

---

src/components/templates/EmptyTemplate/index.tsx
src/constants/HomePageConstants.ts
src/constants/MarketPricePageConstants.ts
src/pages/HomePage.tsx
src/pages/MarketPricePage.tsx

- #223 
1. 정상상태
2. 로딩 및 데이터 없는 경우 나오는 화면

feat: MarketPricePage 컴포넌트 개발

---

src/hooks/useFetchProduct.ts

- #361
서버 재시작 시 상세페이지에서 500에러가 발생하는데 500에러는 별도의 처리를 하지 않아 계속해서 요청을 보내는 오류가 있어 해당 부분을 수정했스빈다.
일단 생각한게 "에러 발생 => 페이지 이동 => 세션 체크 => 오잉? 로그인 안됐네 로그인 페이지로 이동"을 생각하고 만든건데 만약 또 발생하면 그냥 error 페이지로 넘겨버리겠습ㄴ디ㅏ.

fix: 상세페이지 에러 수정

---

src/components/atoms/Button/TextButton/index.tsx
src/components/atoms/Button/TextButton/styled.ts
src/components/organisms/PostItem/index.tsx
src/components/organisms/PostItem/styled.ts
src/components/organisms/PostList/index.tsx
src/components/templates/ChatRoomTemplate/TopSheet.tsx
src/components/templates/TransactionSellTemplate/index.tsx
src/pages/ChatRoomPage.tsx

- #358
- 거래 완료 시 버튼 disabled 처리
- postItem 말줄임 추가
- 일단 임시로 isCompleted로 거래 완료 여부를 파악했는데, 전체적으로 리팩터링하며 깔끔한 방법을 찾으면 좋을 것 같습니다..!

feat: 채팅방 API 거래 완료 여부 추가

---

public/manifest.json

- #375 
- orientation 추가 
-> orientation 필드는 PWA에서 화면 방향을 제어하는 데 사용
```
orientation 필드에는 아래와 같은 값 중 하나를 설정
어떤 방향에서도 앱을 실행
기본값입니다.
"orientation": "any"
장치의 기본 방향(예: 세로 모드가 기본인 스마트폰)에서 실행
"orientation": "natural"
세로 모드(가로 모드 금지)에서 실행됩니다.
"orientation": "portrait"
세로 모드 중 기본 방향(예: 스마트폰을 홈 버튼 방향으로 세로로 들고 있는 상태)에서 실행
"orientation": "portrait-primary"
세로 모드 중 기본 방향의 반대 방향(예: 스마트폰을 상단이 아래로 오게 뒤집은 상태)에서 실행
"orientation": "portrait-secondary"
가로 모드(세로 모드 금지)에서 실행
"orientation": "landscape"
가로 모드 중 기본 방향(예: 스마트폰을 오른쪽으로 눕힌 상태)에서 실행
"orientation": "landscape-primary"
가로 모드 중 기본 방향의 반대 방향(예: 스마트폰을 왼쪽으로 눕힌 상태)에서 실행
"orientation": "landscape-secondary"
```
- launch_handler 필드 구성
launch_handler는 기본적으로 객체이며, client_mode 속성을 포함
```
client_mode
이 속성은 새 창을 열거나 기존 PWA 창에서 요청을 처리할지를 결정합니다.
가능한 값: …
```

deploy: manifest.json 누락된 옵션 추가

---

public/manifest.json

chore: manifest.json 옵션 변경

---

public/.well-known/assetlinks.json
vercel.json

- #375 
배포 후 실제 어플을 핸드폰에 설치했더니 상단의 주소바가 노출되는 현상과 관련해서
.well-known 폴더와 json 및 vercel.json 을 수정하였습니다.

deploy: PWABuilder 상단의 주소줄 제거

---

src/components/organisms/Comment/stories.tsx

- #371 
- Comment API 변동으로 인해서 타입을 변경했는데 .stories 파일에 반영이 누락된 부분 작업했습니다.

fix: Comment storybook 빌드 에러 해결

---

public/manifest.json

- #375 
- 테마 색깔을 하얀색으로 변경해달라는 요청이 있어서 테마 색깔을 #fffff 으로 변경하였습니다.

chore: 테마 색깔 변경

---

public/.well-known/assetlinks.json

PWA Builder 로 제작한 .apk 에서 소셜 로그인시 주소바가 표시되는 문제 관련해서 Test 하는 부분입니다.

test: 웹 주소 표시줄 관련 테스트

---

src/services/apis/auth.ts

PWA Builder 주소 표시줄 테스트 관련 테스트입니다.

test: PWA Builder 주소 표시줄 테스트

---

src/pages/LoginPage.tsx

refactor: 로그인 콜백 경로일 경우 로그인 템플릿을 보여주지 않도록 변경

---

public/.well-known/assetlinks.json

- #375 
- 최종 버전 assetlinks 파일로 교체

deploy: PWA Builder 관련 assetlinks 파일 교체

---

index.html

- #375
manifest.json 으로 테마 색깔 변경 적용이 안되서, index.html meta의 테마 색깔을 변경하였습니다.

chore: index.html 메인 테마 색깔 변경

---

src/components/organisms/CommentItem/index.tsx
src/components/organisms/CommentItem/styled.ts
src/hooks/useFetchBlockedUsers.ts
src/pages/BlockedUsersPage.tsx

- #357
- 1차 PR 후 글과 댓글 차단 테스트 및 이슈 해결
- 글 및 댓글 차단
- 차단 해제

feat: 차단 기능 API 연동 (2차)

---

public/.well-known/assetlinks.json

test: assetlinks 관련 테스트

---

public/.well-known/assetlinks.json

fix: 구글 심사 관련 에셋링크 문제 해결

---

index.html

- #401 
로고 페이지 preload 하는 식으로 변경하였습니다.

refactor: LCP 요소(로고) preload 로 변경
