- src/components/atoms/Input/index.tsx
- src/components/atoms/Input/stories.tsx
- src/components/atoms/Input/styled.ts
- #5
Input 컴포넌트를 작업했습니다.
1. 일반적인 Input
value, setValue를 사용해 Input의 value를 변경합니다.
2. onClick을 사용하는 Input
value, onClick을 사용해 Input의 value를 변경합니다.
3. 다 넣으면?
onClick을 사용하는 Input 방식으로 실행됩니다.
- 기존에 **text라고 이름지었던 부분을 value**로 받았습니다.
- onChange의 경우 함수를 직접 받은 것이 아닌 **setValue를 보내 value만 변경하도록** 만들었기 때문에 이후 **onChange 시 수행되어야 할 액션이 있다면 별도로 추가가 필요**합니다.
- 스타일 이라고 해야 할 부분은 아무것도 적용하지 않고, **onClick이 있는 경우에 cursor만 default에서 pointer**로 변경했습니다.
- _value만 넣었을 때 개발자 도구 상에서 오류 발생하는 지 확인 필요._ 에 대해 **onClick이 있으면 빈 함수** 실행, **onClick이 없으면 handleInputChange**가 실행되도록 만들었습니다.
> feat: Input 컴포넌트 개발

- src/components/atoms/Divider/styled.ts
- src/components/atoms/Text/index.tsx
- src/components/molecules/TextDividerList/index.tsx
- src/components/molecules/TextDividerList/stories.ts
- src/components/molecules/TextDividerList/styled.ts
- src/index.css
- #23 
- #3 #10 
TextDividerList 컴포넌트를 개발했습니다.
- Text 컴포넌트를 수정했습니다.
- lint에 걸리는 FC 제거
- onClick 추가
- Divider 컴포넌트(styled)을 수정했습니다.
- 기본적으로 hr에 적용되어있던 margin 제거
- Text를 바로 사용하지 않고 TextDividerTextWrapper로 묶어서 사용했습니다.
- padding: 0.5rem, hover 시 배경 색상 변경 만 적용되어있습니다.
- 아이템 선택 시 이벤트를 화면쪽에서 생각해보면 items의 타입이 객체 형태가 되는 것이 좋아보이는데(해당하는 동네의 지역코드를 사용해 처리 등등....) 이 부분은 별도로 적용하진 않았습니다. 필요하다면 이후 작업에서 설정이 필요합니다.
> feat: TextDividerList 컴포넌트 개발

- package.json
- src/App.tsx
- src/utils/dayFormatter.ts
- yarn.lock
- #68 
- 물품 상세 페이지 내 경매 마감 시간(남은 시간)으로 바꿔주는 유틸 함수 작성
기존 이슈에서는 00:00:00 으로 나타내기로 되어있었는데, 개발하면서 생각을 해보니 3일이 넘어가는 마감시간의 경우는 사용자 입장에서 날짜를 역산하기 쉽지 않을 거 같아 `XX일 XX시간 XX분 XX초` 형태로 변경하였습니다.  
- n시간 전 유틸 함수 구현(채팅 온 시간이나 글 작성 시간 나타내는 유틸 함수)
해당 부분은 이슈와 동일하게 구현하였습니다.
- utils 폴더 생성하여 dayFormatter.ts에 작성하였습니다.
> feat: day.js 설치 및 남은 시간 formatting 하는 함수 개발

- src/components/molecules/IconWithText_legacy/index.tsx
- src/components/molecules/IconWithText_legacy/stories.ts
- src/components/organisms/CategoryGrid/index.tsx
- src/components/organisms/CategoryGrid/stories.ts
- src/components/organisms/CategoryGrid/styled.ts
- #66 
- CategoryGrid  컴포넌트 개발 완료
- IconwithText 관련해서 legacy로 파일명이 바뀌면서 기존 Storybook에서 해당 경로를 못 찾는 문제가 생겼습니다.
이 부분도 같이 해결해놨습니다.
- 올려드린 처음 사진을 보시면 category 9번의 높이가 늘어지는 현상이 발견되었습니다. 
category 9 보다 category 10 이 1글자 더 많아서 줄바뀜으로 생기는 현상인데, 이걸 위해 별도의 Category Item마다 별도의 Wrapper 씌워주는 방식으로 해결 했습니다. 
CategoryItemWrapper 를 추가한 경우 둘의 결과는 또 동일하게 나오네요.. 일단 마치기전에 말씀드린 부분은 잊어주시죠!
* grid-template-columns: repeat(4, minmax(0, 1fr));
* grid-template-columns: repeat(4, 1fr);
> feat: CategoryGrid 컴포넌트 개발

- src/components/organisms/MyPageMenu/index.tsx
- src/components/organisms/MyPageMenu/stories.ts
- src/components/organisms/MyPageMenu/styled.ts
- src/constants/myPageMenus.ts
- src/types/index.ts
- src/types/navMenu.d.ts
- #45
MyPageMenu 컴포넌트 개발했습니다.
- 마이페이지에서 사용되는 메뉴 목록은 `constants/myPageMenus.ts`에서 관리합니다.
- icon / name / pathname을 사용하는 메뉴의 타입을 별도로 관리하는 것이 좋을 것 같아 `types/navMenu.d.ts`에 작성했습니다.
- key는 임의로 main menu쪽은 `m_root_${idx}`, sub menu쪽은 `m_${idx}_${i}`(부모 인덱스, 자식 인덱스)로 설정했습니다.
> feat: MyPageMenu 컴포넌트 개발

- .eslintrc.cjs
- src/App.tsx
- src/components/molecules/IconWithText_legacy/index.tsx
- src/components/molecules/IconWithText_legacy/stories.ts
- #133 
ESLint 규칙 추가하고, 추가 이후 걸리는 경고 및 오류들을 수정했습니다.
- 사용하지 않는 변수를 underscore(_)로 작성한 코드에 경고를 없애기 위해 선행 underscore 허용했습니다.
```js
{
"@typescript-eslint/naming-convention": [
"error",
{
selector: "parameter",
format: ["camelCase"],
leadingUnderscore: "allow",
},
{
selector: "variable",
format: ["camelCase", "UPPER_CASE", "PascalCase"],
leadingUnderscore: "allow",
},
],
}
```
- `IconWithText_legacy/index.tsx`의 컴포넌트 이름을 `IconWithTextLegacy`로 수정했습니다.
- `App.tsx`에서 가져왔지만 사용되지 않던 `getTimeRemaining`를 제거했습니다.
> chore: Lint 규칙 추가

- src/components/organisms/ChatItem/index.tsx
- src/components/organisms/ChatItem/stories.ts
- src/components/organisms/ChatItem/styled.ts
- #53 
- last msg 길어지면 ... 처리
- lastMsgCnt 의 경우 0인 경우 Badge 컴포넌트 표출 X
- props로 전달 받은 profileImgUrl, itemImgUrl 이 Overlapping Image 컴포넌트에 전달 (Image 컴포넌트의 타입은 "square")
- 구분이 너무 안될 것 같아 hover 추가해뒀습니다.
- isActive 같은 것으로 active 상태가 필요하지 않을까 고민했는데 이 부분은 추후 디자인에서 필요하면 적용하는게 좋을 것 같습니다.
- `<OverlappingImage>` 컴포넌트가 width를 지정하지 않으면 출력이 안되는 것을 확인해서 사용하는 쪽에서 55px로 주었습니다.
> feat: ChatItem 컴포넌트 개발

- src/components/molecules/index.ts
- src/components/organisms/PostImageManager/index.tsx
- src/components/organisms/PostImageManager/stories.tsx
- src/components/organisms/PostImageManager/styled.ts
- src/components/organisms/index.ts
- src/types/image.d.ts
- src/types/index.ts
- #32 
- PostImageManager 컴포넌트 개발
- ImageInfo를 props로 받아 처리하는 방식으로 구현
- url: S3에 업로드 된 이미지 url ex) https://github.com/moypp.png
- base64Url: 아직 S3에 올라가지 않아 미리보기만 제공하는 base64 url
- file: 아직 올라가지 않은 이미지를 나중에 S3에 올리기 위해 필요한 file (S3에 올릴 때는 file을 사용한다고 하여 추가했습니다.)
```ts
export interface ImageInfo {
url?: string;
base64Url?: string;
file?: File;
}
```
- console.log로 보면 이렇게 구성되었습니다.
- 이 방식으로 구현한 이유는 나중에 최종적으로 글을 등록할 때 남아있는 이미지들만 S3에 업로드하면 좋을 것 같아서 구현해봤습니다.
- 일단 이렇게 구현했지만, 상위 컴포넌트 작업하시는 분이 마음대로 수정하시면 될 것 같습니다!
> feat: PostImageManager 컴포넌트 개발

- src/components/organisms/ChatItem/styled.ts
- src/components/organisms/ChatList/index.tsx
- src/components/organisms/ChatList/stories.ts
- src/components/organisms/ChatList/styled.ts
- #56 
-  ChatList 컴포넌트 개발
-  ChatItem 에서 안 읽은 메시지 배지 위치가 이상해서 임의로 오른쪽 끝으로 배치해놨습니다.
> feat: ChatList 컴포넌트 개발

- src/components/molecules/TabMenu/index.tsx
- src/components/organisms/PostList/index.tsx
- src/components/organisms/TransactionOverview/index.tsx
- src/components/organisms/TransactionOverview/stories.tsx
- src/components/organisms/TransactionOverview/styled.ts
- #46 
- TransactionOverview 개발 완료
- Tab 클릭했을 때 PostList의 타입을 바꿀 수 있도록 TabMenu 의 onClick 타입을 변경하였습니다. #24
기존: () => void
변경 : (tab:string) => void  
- (1) 전체 post를 들고 있고, 내부적으로 판매중 / 거래 완료로 필터를 거는 방법과
(2) 판매중 Tab이나 거래완료 Tab 누를 때마다 fetch해오는 방식이 있는데
API 문서 확인하니(https://www.notion.so/prgrms/API-13d3e47046bf81238a6bfe177efb846d?p=13ef34660f81411fab029ba38186ef55&pm=s) 
(2)번 방법으로 진행하신 것 같아 (2)번 방법에 어울리도록 구성하였습니다.
> feat: TransactionOverview 컴포넌트 개발

- .storybook/preview.tsx
- src/components/templates/HomeTemplate/stories.ts
- src/components/templates/HomeTemplate/styled.ts
- src/components/templates/MarketPriceTemplate/index.tsx
- src/components/templates/MarketPriceTemplate/stories.tsx
- src/components/templates/MarketPriceTemplate/styled.ts
- #192 
- 시세 조회 페이지 템플릿 작업
- post 개수가 많아지는 경우 BottomNavBar 고정이 안되는 현상을 발견해서 시세조회쪽이랑 홈쪽 둘 다 수정하였습니다.
- 현재 URL 정보를 제가 임의로 storybook 에 주기 위해 .storybook/preview.tsx 파일 수정하였습니다.
이에 따라 현재 url 정보를 스토리에 파라미터로 전달해줄 수 있습니다.
> feat: MarketPriceTemplate 컴포넌트 개발

- src/App.tsx
- src/components/atoms/Icon/styled.ts
- src/components/organisms/BottomNavBar/index.tsx
- src/components/organisms/BottomNavBar/styled.ts
- src/components/organisms/TopBar/index.tsx
- src/components/organisms/TopBar/styled.ts
- src/components/templates/RootLayout/index.tsx
- src/components/templates/RootLayout/styled.ts
- src/components/templates/index.ts
- src/constants/bottomNavItems.ts
- src/hooks/index.ts
- src/hooks/useSearchTopBar.ts
- src/pages/HomePage.tsx
- src/pages/SearchPage.tsx
- src/pages/SearchResultPage.tsx
- src/router.tsx
- src/stores/headerStore.ts
- src/stores/index.ts
- src/stores/topbarStore.ts
- src/styles/global.tsx
- src/styles/index.ts
- #159
RootLayout 컴포넌트 개발했습니다.
- 초기화 스타일 이외의 공통 스타일 적용을 위해 GlobalStyle 컴포넌트를 만들었습니다.
- RootLayout의 max-width는 375px입니다.
- 각 페이지에서 Header와 TopBar 사용 방법은 Home, Search, SearchResult(useSearchTopBar) 페이지에 적용해두었습니다.
- Header를 사용할 때에는 useHeaderStore의 setTitle을 호출해서 사용합니다.
- TopBar를 사용하는 페이지에서는 useTopBarStore의 각 Set Action(setIcon, setRightClick, setBackClick => default navigate(-1)) 함수들을 호출해서 사용합니다.
- 기본적으로 search에서는 SearchTopBar를 사용하기 때문에 해당 로직은 useSearchTopBar로 분리해두었습니다.
> feat: RootLayout 컴포넌트 개발

- src/components/organisms/PermissionList/styled.ts
- src/components/templates/PermissionRequestTemplate/index.tsx
- src/components/templates/PermissionRequestTemplate/stories.ts
- src/components/templates/PermissionRequestTemplate/styled.ts
- src/components/templates/RootLayout/styled.ts
- #163
- #57 
PermissionRequestTemplate 컴포넌트 개발했습니다.
- 공통 레이아웃 스타일의 PageLayoutWrapper에 display: flex를 추가했습니다. (전체 사이즈를 차지하는 경우를 처리하기 위함 => [참고한 코드](https://codepen.io/dshung1997/pen/LYxvXNy))
- PermissionList의 스타일을 변경했습니다.
- 기존에 375px로 고정된 부분 제거 (이후 공통 레이아웃에서 처리됨)
- height 100%, justify-content space-between
- permission-con의 min-height를 제거하고 flex-1 추가
> feat: PermissionRequestTemplate 컴포넌트 개발

- src/components/organisms/BlockedUserItem/index.tsx
- src/components/organisms/BlockedUsersList/index.tsx
- src/components/organisms/BlockedUsersList/stories.ts
- src/components/organisms/BlockedUsersList/styled.ts
- src/components/templates/BlockedUsersTemplate/index.tsx
- src/components/templates/BlockedUsersTemplate/stories.tsx
- src/components/templates/BlockedUsersTemplate/styled.ts
- src/types/index.ts
- src/types/profile.d.ts
- #182
- BlockedUsersTemplate 컴포넌트 개발
- 컴포넌트 내의 type을 파일로 분리하고, IBlockedUserItem onClick 타입을 `(index: number) => void;`로 수정했습니다.
- 보니까 템플릿과 페이지가 props를 그대로 받아오는 경우가 많아서, 나중에 따로 type으로 분리해야 할 것 같습니다. 어떻게 분리할지는 생각을 해봐야 할 것 같습니다. (템플릿 interface만 template.d.ts로 뺀다던지..?, 아니면 각 비슷한 주제의 파일에 끼워넣기?)
> feat: BlockedUsersTemplate 컴포넌트 개발

- src/components/atoms/Icon/NoIcon/index.tsx
- src/components/atoms/Icon/NoIcon/stories.ts
- src/components/atoms/Icon/NoIcon/styled.ts
- src/components/atoms/Icon/index.ts
- src/components/organisms/TopBar/index.tsx
- src/components/organisms/TopBar/stories.tsx
- src/components/organisms/TopBar/styled.ts
- src/components/templates/RootLayout/index.tsx
- src/hooks/useSearchTopBar.ts
- src/stores/topbarStore.ts
- #215 
TopBar 컴포넌트를 수정했습니다.
Template를 페이지에 넣어보며 테스트하던 중 TopBar 모양이 깨지는 것을 확인했고, 고치려고 만지다가 RootLayout에 넣은 clear 함수때문에 계속해서 TopBar가 초기화되는 현상을 확인해 해당 이슈를 수정했습니다.
또한 살짝 불편하다고 느낀 우측 아이콘 설정 함수들을 하나로 묶었습니다.
기존에 icon이 없다면 RightIcon을 아예 보여주지 않아 backIcon, title만 있을 때 이상하게 보였습니다. 
해당 스타일을 고치기 위해 `NoIcon`이라는 아무것도 없는 아이콘을 추가해 rightIcon이 기본적으로 해당 아이콘을 갖도록 수정했습니다.
RootLayout에서 pathname이 변경될 때마다 TopBar를 초기화하도록 만들었는데 해당 함수가 의도한대로(초기화 -> 화면에서 setTitle.....) 동작하지 않아 제거했습니다.
이후 해당 함수는 사용될 수 있을 것 같아 제거하진 않고, rightIcon의 icon과 onRightClick의 값을 초기화하는 함수로 변경했습니다. (기존에는 title도 초기화)
기존에 만들었던 함수는 setIcon, setRightClick 2개로 분리해서 사용했는데, right icon이 있다면 right click 이벤트도 존재할 것이라 생각하여 두 함수를 묶어 setRightIcon 함수로 변경했습니다.
해당 함수 사용법은 아래와 같습니다.
```tsx
const Example = () => {
const { setRightIcon } = useTopBarStore(); // …
```
> fix: TopBar 수정

- src/pages/OAuthCallbackPage.tsx
- src/pages/ProfileRegistrationPage.tsx
- src/services/apis/user.ts
- src/stores/userStore.ts
- src/types/response/auth.d.ts
- src/types/response/user.d.ts
- src/types/user.d.ts
- #262
로그인 백엔드 연동했습니다.
로그인 시 nickname, profileImage, 선택한 동네 정보가 넘어오는데 해당 정보를 zustand를 통해 저장하도록 설정했습니다.
- 프로필 등록은 API 확인 후 다시 올리겠습니다.
> feat: 로그인 / 프로필 등록 백엔드 연동

- src/constants/queryKeys.ts
- src/hooks/index.ts
- src/hooks/useFetchSession.ts
- src/pages/guards/AuthGuard.tsx
- src/pages/guards/LoginGuard.tsx
- src/pages/guards/RequiredGuard.tsx
- src/pages/guards/index.ts
- src/router.tsx
- src/services/apis/user.ts
- src/types/response/user.d.ts
- #306
RouteGuard 적용했습니다.
Guard는 3종류로 나눠집니다.
1. 로그인한 상태의 사용자가 로그인 페이지 접근 시 /으로 리다이렉트 (로그인 체크해서 ㅇㅇ면 홈으로)
2. 로그인은 했지만 필수로 입력해야하는 값을 입력하지 않은 경우 페이지(프로필 등록, 동네 등록) (로그인만 체크)
3. 로그인한 상태의 사용자가 필수 입력값도 다 입력한 경우 모든 페이지 접근 가능 (로그인 체크, 필수 입력값 체크)
이제 로그아웃 없으면 자유롭게 로그인이 불가능해집니다 ㅠ..
카카오 신규 회원가입으로 등록해서 테스트 했을 때에는 큰 문제 없었습니다. 하지만 혹시라도 오류가 발생한다거나 하얀 화면만 나온다거나하면 꼭 말씀해주세요.....!
> feat: RouteGuard 적용

- src/components/organisms/Modal/styled.ts
- src/components/organisms/TopBar/styled.ts
- #321
- TopBar 제목이 길어졌을 때 1줄만 나오도록 수정했습니다.
- 모달 배경이 모바일 사이즈로 작아졌을 때 비어보이던 현상을 수정했습니다.
- PostItem의 경우 수정하려고 확인해보니 대공사가 될 것 같아 수정하지 않았습니다.
| Before | After |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/484bd37c-2d3b-4aae-94e9-d5624c76b2d3) | ![image](https://github.com/user-attachments/assets/101f0e66-5cbd-4941-87d4-18d05dac3eb0) |
| ![image](https://github.com/user-attachments/assets/8547ce2f-6971-4c32-94de-97ca46d0dff0) | ![image](https://github.com/user-attachments/assets/b0ea5da0-c848-4eef-91fd-b255e2107f4c) |
> fix: 디자인 어색한부분 수정

- src/components/organisms/CommentItem/index.tsx
- src/constants/modalMessage.ts
- src/hooks/useDetailModal.ts
- src/hooks/useFetchProduct.ts
- src/pages/DetailPage/index.tsx
- #247
- 삭제 모달 추가했습니다. (이전에 구매자 있을 때 삭제 막았던 부분도 모달 추가했습니다 => 삭제 가능) 디자인은 전혀 적용 안했습니다...!
- 에러 상황(삭제된 물건 페이지, 404)일 때 리다이렉트 로직 추가했습니다.
- 조기마감 이후 상품 상세페이지 다시 가져오도록 수정했습니ㅏㄷ.
- 댓글 이미지 null인 경우 로고 이미지를 사용하도록 수정했습니다.
> feat: 상세페이지 작업 (8차)

- src/constants/queryKeys.ts
- src/hooks/index.ts
- src/hooks/useFetchTransactions.ts
- src/pages/TransactionPage.tsx
- src/services/apis/index.ts
- src/services/apis/transaction.ts
- src/types/response/index.ts
- src/types/response/transaction.d.ts
- #347
구매내역 API 연동했습니다.
- 현재 API가 제대로 동작하는지는 확인중입니다.
- Empty Template를 일단!! 적용하지 않았습니다. (조금 더 확인해보고 적용)
- 판매내역쪽에서 `Warning: Encountered two children with the same key, '-1'.`가 발생하는데 백엔드에서 보내주는 데이터에 productId가 없어서 발생하는 오류입니다. 이후 productId가 추가되면 수정이 필요하지 않고, 추가되지 않는다면 index를 넘겨서 처리하도록 수정하겠습니다.
- 남은시간 over도 이후 수정하겠습니다.
> feat: 구매내역 API 연동 (1차)

- src/pages/ChatRoomPage.tsx
- src/services/apis/product.ts
- #351
- 거래 완료 api 연동
- api만 연동하였기 때문에 아래와 같은 작업이 추가로 필요합니다.
1. 거래 완료를 누를 시 버튼이 `disabled`로 바뀌며 '거래 완료'가 아닌 다른 안내 text로 바뀌도록 수정하기 (`PostList` 수정 필요)
2. 백엔드에서 채팅하는 물품의 거래 완료 여부 상태를 추가로 받아오기 (백엔드와 api 논의 필요) 
- 뮤테이션을 적용하려 했는데, 게시글 등록 form에 먼저 적용해보고, 추후에 다른 곳에도 적용해 놓겠습니다..!
> feat: 거래 완료 api 연동

- src/components/organisms/PostItem/index.tsx
- src/pages/TransactionPage.tsx
- #347
- key 때문에 오류나던 부분 수정
- timeRemaining 값이 over일 때 종료로 보이도록 수정
- empty template을 적용하기 위해서는 TransactionOverview부터 수정이 필요해 우선 보류했습니다.
- 판매중 => 글을 올렸지만 판매되지 않은(거래완료/삭제되지 않은) 내역
- 거래완료 => 글을 올리고 판매가 완료된(거래완료된) 내역
> feat: 판매내역 API 연동 (2차)

- src/components/organisms/AuctionBidBottomSheet/index.tsx
- src/components/organisms/AuctionBidBottomSheet/styled.ts
- src/components/organisms/PostRegisterForm/index.tsx
- #352
20억 초과 입력 시 처리했습니다. (AuctionBidBottomSheet, PostRegisterForm)
1. 현재 입력된 price가 20억 넘는지 확인
2. 20억 넘으면 버튼 disabled & 에러메시지 활성화
1. minimumPrice의 validate에 checkValue에서 20억 넘는지 확인
2. 20억 넘으면 error메시지에 (자동)추가
AuctionBidBottomSheet에서 다른 입력값을 처리하는 부분들도 이후 다 이런식으로 처리하면 좋겠습니다~~!
> feat: 20억 초과 입력 시 처리

- src/components/organisms/Comment/index.tsx
- src/components/organisms/CommentItem/index.tsx
- src/components/organisms/PostItem/index.tsx
- src/constants/modalMessage.ts
- src/hooks/useDetailModal.ts
- src/pages/DetailPage/index.tsx
- src/services/apis/user.ts
- src/types/response/comment.d.ts
- src/types/user.d.ts
- #371 
- 기존 문구 변경
**댓글**
차단하기 -> 유저 차단하기
신고하기 -> 유저 신고하기
**게시글**
차단하기 -> 유저 차단하기
신고하기 -> 유저 신고하기
- 신고하기 API 연동 완료
- useDetailModal 훅 쪽에 confirm 모달 콜백함수로 TODO 작성된 부분이 있어 이 부분을 최대한 활용했습니다.
- 신고하기 요청 자체를 user 에 대한 신고로 보고 user api 쪽에 신고하는 API 추가했습니다.
- 신고할때 별도의 form 에 입력받지 않고 있기 때문에, 임의로 request 내용을 구성하도록 했습니다.
(댓글의 경우 댓글 내용포함, 게시글의 경우 게시글 제목, 게시글 내용 포함)
이 부분은 이후에 변경이 필요할 수도 있을 것 같습니다.
> feat: 신고하기 API 연동

- build.sh
- #395 
레포 이관으로 인해  build.sh 파일에 있던 폴더명이 기존 레포이름을 따라가고 있어서 생기는 문제였습니다.
해당 부분 수정하는 PR입니다.
없습니다.
> fix: build.sh 디렉토리 명 변경
